In [17]:
# __init__ is the constructor that runs when an object is created
# self refers to the current object

# self.X = X means storing input X inside the object
# so it can be accessed later using object.X

# variables without self are local and cannot be accessed later

In [18]:
# layers are defined in __init__ using self (e.g., self.fc1)
# in forward(), we use self.fc1 because it belongs to the model

# self = current model object
# self.fc1(x) means using the stored layer on input x

In [19]:
# layers are defined in __init__ using self (e.g., self.fc1)
# in forward(), we use self.fc1 because it belongs to the model

# self = current model object
# self.fc1(x) means using the stored layer on input x

In [20]:
# Dataset defines how to access individual samples from data

# __len__() returns total number of samples
# __getitem__(idx) returns one sample (X[idx], y[idx])

# Dataset stores references to data (in RAM or file paths)
# it does NOT necessarily store full data in memory

In [21]:
# DataLoader uses Dataset to load data in batches

# it provides:
# - batching (batch_size)
# - shuffling (shuffle=True)
# - iteration during training

# Dataset → single sample
# DataLoader → batch of samples

In [22]:
# reshape(-1,1) converts a 1D tensor (n,) into a 2D column tensor (n,1)

# -1 → automatically determine number of rows
#  1 → one column

# used to match model output shape (batch_size, 1)

In [23]:
# nn.Linear(in_features, out_features)

# performs: y = xW^T + b

# weights and bias are initialized randomly (float32, requires_grad=True)

In [24]:
# torchvision.transforms is used for preprocessing and augmentation

# similar to ImageDataGenerator in TensorFlow

# transforms are applied inside Dataset

In [25]:
# local variables exist only inside a function and are destroyed after it ends,
# but self.variable stores data inside the object so it can be accessed later

In [ ]:
# Dataset does not necessarily store data in RAM;
# it stores how to access data (either from memory or from disk)
# and provides individual samples using __getitem__()

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
X , y = make_classification(
    n_samples = 10,
    n_features = 2,
    n_informative = 2,
    n_redundant = 0,
    n_classes = 2,
    random_state = 42

)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
x=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [9]:
from torch.utils.data import Dataset , DataLoader

In [10]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [11]:
dataset = CustomDataset(X,y)

In [12]:
len(dataset)

10

In [14]:
dataset[2]

(array([-2.8953973 ,  1.97686236]), tensor(0))

In [26]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [27]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print('-----------------')

tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([1, 1])
-----------------
tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([1, 0])
-----------------
tensor([[-1.9629, -0.9923],
        [ 1.8997,  0.8344]], dtype=torch.float64)
tensor([0, 1])
-----------------
tensor([[-0.9382, -0.5430],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([1, 0])
-----------------
tensor([[-2.8954,  1.9769],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([0, 0])
-----------------
