# nn module(single neuron)

In [ ]:
#create model class
#5input + 1bias -> 1output
import torch
import torch.nn as nn

class Model(nn.Module):
  #inheriting the utilities from nn.module
  def __init__(self,num_features):
    super().__init__()
    self.lin = nn.Linear(num_features,1)#input features,output features
    self.sig = nn.Sigmoid()

  def forward(self,features):
    out = self.lin(features)
    out = self.sig(out)

    return out


In [ ]:
#create dataset
features = torch.rand(10,5)
#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)#tp call forward pass it is a magic function


tensor([[0.6124],
        [0.6547],
        [0.6534],
        [0.6602],
        [0.6014],
        [0.5472],
        [0.6608],
        [0.6137],
        [0.6637],
        [0.6901]], grad_fn=<SigmoidBackward0>)

In [ ]:
features.shape[1]

5

In [ ]:
#show model weights
model.lin.weight

Parameter containing:
tensor([[ 0.1227,  0.1450,  0.4357,  0.1495, -0.4266]], requires_grad=True)

In [ ]:
model.lin.bias

Parameter containing:
tensor([0.3368], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# nn.module using hidden layer

In [ ]:
class Model2(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,3)
    self.rel = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sig = nn.Sigmoid()

  def forward(self,features):

    out = self.linear(features)
    out = self.rel(out)
    out = self.linear2(out)
    out = self.sig(out)

    return out

In [ ]:
#create dataset
features = torch.rand(10,5)
#create model
model = Model2(features.shape[1])

#call model for forward pass
model(features)#tp call forward pass it is a magic function


tensor([[0.4909],
        [0.4888],
        [0.5258],
        [0.4716],
        [0.4716],
        [0.5000],
        [0.4773],
        [0.4677],
        [0.4965],
        [0.5077]], grad_fn=<SigmoidBackward0>)

In [ ]:
features

tensor([[0.0392, 0.9985, 0.4929, 0.0802, 0.8318],
        [0.9703, 0.4242, 0.3886, 0.5958, 0.3182],
        [0.2940, 0.6628, 0.5820, 0.3940, 0.0709],
        [0.8768, 0.5993, 0.4555, 0.5682, 0.7166],
        [0.4458, 0.1231, 0.1477, 0.2149, 0.9159],
        [0.1275, 0.7145, 0.8266, 0.0108, 0.0966],
        [0.6136, 0.1671, 0.9154, 0.7255, 0.4125],
        [0.1783, 0.9651, 0.5222, 0.7007, 0.3636],
        [0.0794, 0.1927, 0.9626, 0.4527, 0.5979],
        [0.7803, 0.4578, 0.0067, 0.5109, 0.6248]])

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.4346,  0.2300,  0.2206, -0.1421, -0.3429],
        [-0.0134, -0.0324, -0.3604,  0.3469, -0.3249],
        [-0.2780,  0.1839, -0.3379,  0.2743, -0.3658]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[ 0.5259, -0.3014, -0.1104]], requires_grad=True)

In [ ]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential Containers

In [ ]:
class Model2(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):

    out = self.network(features)

    return out

In [ ]:
#create dataset
features = torch.rand(10,5)
#create model
model = Model2(features.shape[1])

#call model for forward pass
model(features)#tp call forward pass it is a magic function


tensor([[0.5979],
        [0.6009],
        [0.5930],
        [0.6029],
        [0.5971],
        [0.6043],
        [0.5938],
        [0.6044],
        [0.6000],
        [0.5963]], grad_fn=<SigmoidBackward0>)