In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using gpu:{torch.cuda.get_device_name(0)}")
else:
  print("gpu is not available.Using Cpu")

GPU is available
using gpu:Tesla T4


# Creating Tensor

In [ ]:
#using empty -> creating a tensor of a given shape without initializing values.
torch.empty(2,3)#memory is allocated but values are random garbage values and these values are not by random caluclation - they are whatever was in a memory before

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x=torch.empty(3,3)
x.fill_(5)
print(x)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


In [ ]:
x.dtype

torch.float32

In [ ]:
#check tyoe
type(x)

torch.Tensor

In [ ]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
s=torch.zeros(2,4,3)

In [ ]:
import torch
s = torch.zeros(2,4,3)
s.ndim

3

In [ ]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#rand is a function where it will give random values between 0 and 1
torch.rand(2,3)

tensor([[0.8558, 0.4814, 0.2455],
        [0.6966, 0.4808, 0.6789]])

In [ ]:
#use of seed
#even we run it n number of times we get the same value

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
#custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways
print("using arange ->",torch.arange(0,10,2))#it will print values from start to end-1 in given range and 3rd value is step skipping those many values
print()
#using linspace
print("using linspace ->",torch.linspace(0,10,10))#it will print evenly space values in given range and 3rd value represents how many values you need


using arange -> tensor([0, 2, 4, 6, 8])

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
#identity matrix
print("using eye:",torch.eye(5))#creates a 5x5 identity matrix

using eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


# Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
#copying the shape of an tensor
torch.empty_like(x)

tensor([[        0, 280288608,         0],
        [        0,         0,         0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# Tensor DataTypes

In [ ]:
x.dtype

torch.int64

In [ ]:
#assign datatype while creating itself
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#if we want to convert tensor datatype which is already instialized
x=x.to(torch.float32)

In [ ]:
x.dtype

torch.float32

In [ ]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Oprations

In [ ]:
x=torch.rand(2,3)

In [ ]:
x

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [ ]:
#addition
x+4

tensor([[4.2239, 4.3023, 4.1784],
        [4.8238, 4.5557, 4.9770]])

In [ ]:
#subtraction
x-2

tensor([[-1.7761, -1.6977, -1.8216],
        [-1.1762, -1.4443, -1.0230]])

In [ ]:
#multiplication
x*3

tensor([[0.6717, 0.9070, 0.5353],
        [2.4715, 1.6672, 2.9311]])

In [ ]:
#divison
x/3

tensor([[0.0746, 0.1008, 0.0595],
        [0.2746, 0.1852, 0.3257]])

In [ ]:
(x+4)//3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
x**2

tensor([[0.0501, 0.0914, 0.0318],
        [0.6787, 0.3089, 0.9546]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [ ]:
print(a)
print(b)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])


In [ ]:
#addition
a+b

tensor([[0.9717, 1.1950, 1.5354],
        [0.9127, 0.2595, 0.9212]])

In [ ]:
#subtraction
a-b

tensor([[-0.0837,  0.7007, -0.0464],
        [ 0.0657,  0.2257,  0.4794]])

In [ ]:
#multiplication
a*b

tensor([[0.2343, 0.2343, 0.5888],
        [0.2072, 0.0041, 0.1547]])

In [ ]:
a/b

tensor([[ 0.8415,  3.8346,  0.9413],
        [ 1.1552, 14.3533,  3.1705]])

In [ ]:
a//b

tensor([[ 0.,  3.,  0.],
        [ 1., 14.,  3.]])

In [ ]:
a**b

tensor([[0.6515, 0.9868, 0.7919],
        [0.7388, 0.9763, 0.9243]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
torch.abs(c)#it will convert all values into positive value

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)#it will multiply all values with-1

tensor([-1,  2, -3,  4])

In [ ]:
#round
d=torch.tensor([1.9,2.5,3.2,4.8])

In [ ]:
torch.round(d)

tensor([2., 2., 3., 5.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
s=torch.tensor([25,16,28,20])

In [ ]:
#when we want to convert the values into range, like a defined tensor if we want to keep it in a range we can use clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.5000, 3.0000, 3.0000])

In [ ]:
torch.clamp(s,min=15,max=18)#clamp keeps the value inside range,only changes if it is  outside than it will change

tensor([18, 16, 18, 18])

# Reduction Operation

In [ ]:
#we will only get integers in the range we gave or we defuned
e = torch.randint(size=(2,3),low = 0, high = 10,dtype=torch.float32)

In [ ]:
e

tensor([[3., 9., 4.],
        [0., 5., 7.]])

In [ ]:
#sum -> will give matrix sum
print(torch.sum(e))
#sum along columns
print(torch.sum(e,dim = 0))
#sum along rows
print(torch.sum(e,dim=1))

tensor(28.)
tensor([ 3., 14., 11.])
tensor([16., 12.])


In [ ]:
torch.mean(e)


tensor(4.6667)

In [ ]:
torch.mean(e,dim=0)

tensor([1.5000, 7.0000, 5.5000])

In [ ]:
#median
torch.median(e)

tensor(4.)

In [ ]:
#max and min
torch.max(e)

tensor(9.)

In [ ]:
torch.min(e)

tensor(0.)

In [ ]:
#product
torch.prod(x)

tensor(0.0054)

In [ ]:
#standard deviation
torch.std(x)

tensor(0.3328)

In [ ]:
#variance
torch.var(e)

tensor(9.8667)

In [ ]:
#will give position of the highest value number in defined tensor
torch.argmax(e)

tensor(1)

In [ ]:
#will give position of the least value number in defined tensor
torch.argmin(e)

tensor(3)

# Matrix Operations

In [ ]:
f = torch.randint(size=(2,3),low = 0, high = 10)

In [ ]:
g = torch.randint(size=(3,2),low=0,high=299)

In [ ]:
print(f)
print()
print(g)

tensor([[5, 9, 9],
        [7, 5, 9]])

tensor([[230, 189],
        [ 70,  97],
        [ 64, 148]])


In [ ]:
##matrix multiplication
torch.matmul(f,g)

tensor([[2356, 3150],
        [2536, 3140]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [ ]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [ ]:
h

tensor([[7., 7., 8.],
        [3., 6., 1.],
        [5., 5., 0.]])

In [ ]:
torch.det(h)

tensor(-120.)

In [ ]:
torch.inverse(h)

tensor([[ 4.1667e-02, -3.3333e-01,  3.4167e-01],
        [-4.1667e-02,  3.3333e-01, -1.4167e-01],
        [ 1.2500e-01,  7.4506e-09, -1.7500e-01]])

# Comparison Operations

In [ ]:
i = torch.randint(size=(2,3),low = 0,high = 10)
j = torch.randint(size=(2,3),low = 0,high = 10)

print(i)
print()
print(j)

tensor([[4, 3, 8],
        [8, 3, 3]])

tensor([[5, 0, 6],
        [4, 0, 8]])


In [ ]:
#greater than
print(i>j)
print()
#less than
print(i<j)
print()
#equal to
print(i==j)
print()
#not equal to
print(i!=j)

#greater than equal to




tensor([[False,  True,  True],
        [ True,  True, False]])

tensor([[ True, False, False],
        [False, False,  True]])

tensor([[False, False, False],
        [False, False, False]])

tensor([[True, True, True],
        [True, True, True]])


# Special Functions

In [ ]:
k = torch.randint(size=(2,3),low = 0,high=10,dtype=torch.float32)

In [ ]:
k

tensor([[4., 7., 2.],
        [3., 8., 5.]])

In [ ]:
#log
torch.log(k)

tensor([[1.3863, 1.9459, 0.6931],
        [1.0986, 2.0794, 1.6094]])

In [ ]:
#exp
torch.exp(k)

tensor([[  54.5981, 1096.6332,    7.3891],
        [  20.0855, 2980.9580,  148.4132]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[2.0000, 2.6458, 1.4142],
        [1.7321, 2.8284, 2.2361]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9991, 0.8808],
        [0.9526, 0.9997, 0.9933]])

In [ ]:
torch.softmax(k, dim = 0)#must give dimension and also it only works for float

tensor([[0.7311, 0.2689, 0.0474],
        [0.2689, 0.7311, 0.9526]])

# Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print()
print(n)


tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])


In [ ]:
m+n # new tensor created in the memory , so if we take a dataset and represent it with tensor and if you do a tensor operation on it , it will create a new tensor it will be problematic so we make the changes in tensor itself

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [ ]:
m.add_(n)#inplace operation

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [ ]:
print(m)#inplace operation

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])


In [ ]:
m.relu_()

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [ ]:
m

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

# Copying a tensor

In [ ]:
a = torch.rand(2,3)

In [ ]:
a

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
b = a

In [ ]:
a[0][0]=0

In [ ]:
b

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
a

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
id(a)

135773494243040

In [ ]:
id(b)

135773494243040

In [ ]:
b = a.clone()#to copy tensor values above it pointed to same reference point, now it will only copy values


In [ ]:
b

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
a[0][0]=2

In [ ]:
a

tensor([[2.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
b

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
id(a)

135773494243040

In [ ]:
id(b)

135768570815552

# Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
#creating a tensor on gpu
torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
#moving an existing tensor from cpu to gpu

In [ ]:
a = torch.rand(2,3)

In [ ]:
a#there is no device in the output we got

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [ ]:
b=a.to(device)

In [ ]:
b

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]], device='cuda:0')

In [ ]:
b + 5

tensor([[5.3957, 5.6017, 5.4234],
        [5.5224, 5.4175, 5.0340]], device='cuda:0')

In [ ]:
import time
size = 10000
matrix1 = torch.rand(size,size)
matrix2 = torch.rand(size,size)

start_time = time.time()
result_cpu=torch.matmul(matrix1,matrix2)
cpu_time=time.time()-start_time
print(f"Time on CPU: {cpu_time:.4f} seconds")

matrix1_gpu = matrix1.to('cuda')
matrix2_gpu = matrix2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix1_gpu,matrix2_gpu)
torch.cuda.synchronize()
gpu_time = time.time() - start_time
print(f"time on gpu:{gpu_time:.4f} seconds")

#compare results
print(cpu_time/gpu_time)



Time on CPU: 16.8802 seconds
time on gpu:0.6379 seconds
26.460814993128846


# Reshaping Tensors

In [ ]:
a = torch.ones(4,4)

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#a flatten
torch.flatten(a)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)#0,#1,#2

In [ ]:
b

tensor([[[0.6763, 0.4254, 0.2375, 0.5430],
         [0.1174, 0.6532, 0.5115, 0.3094],
         [0.7907, 0.7351, 0.2693, 0.8009]],

        [[0.5839, 0.0061, 0.4671, 0.8243],
         [0.2861, 0.7459, 0.8487, 0.4059],
         [0.2883, 0.2220, 0.6423, 0.7098]]])

In [ ]:
b.shape

torch.Size([2, 3, 4])

In [ ]:
#permute
b.permute(2,0,1).shape#above when we created value those dimension will have indices,with those indices here we define new dimension , so whatever dimension value is there in the instialized tensor will replace the indices value in this function

torch.Size([4, 2, 3])

In [ ]:
#unsqueeze
#image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape#when you want to add a dimension

torch.Size([1, 226, 226, 3])

In [ ]:
s=torch.rand(3,3,3)

In [ ]:
s

tensor([[[0.5344, 0.3673, 0.9286],
         [0.0528, 0.3753, 0.2057],
         [0.5643, 0.4419, 0.5215]],

        [[0.6743, 0.0401, 0.7158],
         [0.0702, 0.4443, 0.6302],
         [0.6179, 0.1797, 0.3512]],

        [[0.0083, 0.1996, 0.9616],
         [0.6520, 0.2396, 0.8719],
         [0.0902, 0.7858, 0.1384]]])

In [ ]:
print(c)

tensor([[[0.5644, 0.4549, 0.0729],
         [0.8535, 0.9793, 0.0611],
         [0.1162, 0.7666, 0.8801],
         ...,
         [0.9756, 0.1175, 0.9696],
         [0.4014, 0.8289, 0.4343],
         [0.8286, 0.0097, 0.4689]],

        [[0.7481, 0.6284, 0.7681],
         [0.0715, 0.2858, 0.5235],
         [0.9161, 0.3424, 0.8958],
         ...,
         [0.5775, 0.4705, 0.8696],
         [0.3757, 0.1533, 0.9881],
         [0.4648, 0.2386, 0.8656]],

        [[0.7935, 0.3718, 0.3230],
         [0.1845, 0.5999, 0.0242],
         [0.8021, 0.0467, 0.3780],
         ...,
         [0.1834, 0.4347, 0.9546],
         [0.4763, 0.9341, 0.2866],
         [0.7366, 0.5174, 0.5281]],

        ...,

        [[0.1218, 0.2787, 0.6245],
         [0.1088, 0.8578, 0.7249],
         [0.4733, 0.5072, 0.3566],
         ...,
         [0.5109, 0.0817, 0.7453],
         [0.4627, 0.4627, 0.2822],
         [0.9050, 0.8155, 0.4537]],

        [[0.5552, 0.6658, 0.5265],
         [0.1098, 0.8570, 0.6217],
         [0.

In [ ]:
s=(2,3,4)#2 means depth ,3means rows,4 means columns

In [ ]:
d = torch.rand(1,20)#removes dimension

In [ ]:
d.squeeze(0).shape

torch.Size([20])

# Numpy and pytorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])

In [ ]:
b=a.numpy()

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,4])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 4])

# Auto Grad

In [1]:
import torch

In [2]:
x = torch.tensor(3.0,requires_grad=True)#leaf tensor

In [3]:
y = x**2#non leaf tensor


In [4]:
print(y)#every non leaf tensor has grad_fn it stores what opearation made this function so that while doing backward propagation it will know how to compute gradient
print()
print(x)

tensor(9., grad_fn=<PowBackward0>)

tensor(3., requires_grad=True)


In [5]:
y.backward()#dy/d(leaf tesnors) means differentiation of y wrt to all leaf tensors and stored in leaf_tensor.grad

In [6]:
print(x.grad)

tensor(6.)


In [7]:
#grad_fn = operations+link to previous tensors

In [8]:
print(y.grad_fn)

In [9]:
print(x.grad_fn)

None


In [10]:
x1=torch.tensor(3.0,requires_grad=True)
y=x1**2
z=torch.sin(y)


In [11]:
print(x1)
print()
print(z)

tensor(3., requires_grad=True)

tensor(0.4121, grad_fn=<SinBackward0>)


In [12]:
z.backward()

In [13]:
print(x1.grad)

tensor(-5.4668)


In [14]:
def binary_cross_entropy_loss(prediction,target):
  epislon = 1e-8
  prediction = torch.clamp(prediction,epislon,1-epislon)
  return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

In [15]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [16]:
w = torch.tensor(1.0,requires_grad = True)
b = torch.tensor(0.0,requires_grad = True)

In [17]:
w

tensor(1., requires_grad=True)

In [18]:
b

tensor(0., requires_grad=True)

In [19]:
z = w*x + b

In [20]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [21]:
y_pred = torch.sigmoid(z)

In [22]:
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [23]:
loss = binary_cross_entropy_loss(y_pred,y)

In [24]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [26]:
loss.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [27]:
print(w.grad)

tensor(6.6918)


In [28]:
print(b.grad)

tensor(0.9988)


In [29]:
#vector input tensors
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [51]:
x

tensor([1., 2., 3.], requires_grad=True)

In [52]:
y = (x**2).sum()#I compute sum(y) to make the output scalar, and backward computes gradeint of sum(y) with respect to x

In [53]:
y

tensor(14., grad_fn=<SumBackward0>)

In [54]:
y.backward()

In [55]:
print(x.grad)

tensor([2., 4., 6.])


In [56]:
#clearing grad
#In PyTorch,during each forward-backward pass the inputs may change but the model parameters remain the same,so gradeints got accumulated in .grad attribute of those paramter tensors;therefore we optimizer.zero_grad() to clear previous gradients before the next iteration to prevent unwanted accumulation
x.grad.zero_()

tensor([0., 0., 0.])

# Disable Tracking

In [ ]:
#We disable gradient tracking using torch.no_grad() when we do not need backpropagation(such a during prediction),because autograd normally stores intermidiate values to compare gradients,which increases memory,usage,reduces memory consumptio,and speeds up computation for large neural networks

In [59]:
x.requires_grad_(False)

tensor([1., 2., 3.])

In [60]:
y = x**2

In [61]:
y

tensor([1., 4., 9.])

In [64]:
print(y.grad_fn)

None


In [65]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
#detach method

In [66]:
x = torch.tensor(2.0,requires_grad = True)

In [67]:
z = x.detach()
z#here we make completely create a new tensor and it completely came out of the computation graph with same x value

tensor(2.)

In [68]:
y = x**2

In [69]:
y

tensor(4., grad_fn=<PowBackward0>)

In [70]:
y1 = z**2

In [71]:
y1

tensor(4.)

In [72]:
y.backward()#this works

In [73]:
y1.backward()#this will not work

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [74]:
#torch.no_grad()
x = torch.tensor(2.0,requires_grad=True)

In [75]:
with torch.no_grad():
  y = x**2


In [76]:
y

tensor(4.)

In [77]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn