In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using gpu:{torch.cuda.get_device_name(0)}")
else:
  print("gpu is not available.Using Cpu")

GPU is available
using gpu:Tesla T4


# Creating Tensor

In [148]:

#using empty -> creating a tensor of a given shape without initializing values.
torch.empty(2,3)#memory is allocated but values are random garbage values and these values are not by random caluclation - they are whatever was in a memory before

tensor([[1.4542e+01, 4.4767e-41, 6.6860e+00],
        [4.4767e-41, 2.1636e-35, 4.4766e-41]])

In [4]:
x=torch.empty(3,3)
x.fill_(5)
print(x)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


In [5]:
x.dtype

torch.float32

In [6]:
#check tyoe
type(x)

torch.Tensor

In [7]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.zeros(2,4,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [9]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
#rand is a function where it will give random values between 0 and 1
torch.rand(2,3)

tensor([[0.9106, 0.8856, 0.8811],
        [0.8288, 0.2346, 0.0882]])

In [11]:
#use of seed
#even we run it n number of times we get the same value

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [14]:
#custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
#other ways
print("using arange ->",torch.arange(0,10,2))#it will print values from start to end-1 in given range and 3rd value is step skipping those many values
print()
#using linspace
print("using linspace ->",torch.linspace(0,10,10))#it will print evenly space values in given range and 3rd value represents how many values you need


using arange -> tensor([0, 2, 4, 6, 8])

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [16]:
#identity matrix
print("using eye:",torch.eye(5))#creates a 5x5 identity matrix

using eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


# Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
#copying the shape of an tensor
torch.empty_like(x)

tensor([[    0,     0, 65536],
        [    0,     0,   113]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# Tensor DataTypes

In [24]:
x.dtype

torch.int64

In [25]:
#assign datatype while creating itself
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1.0,2.0,3.0],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
#if we want to convert tensor datatype which is already instialized
x=x.to(torch.float32)

In [28]:
x.dtype

torch.float32

In [29]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Oprations

In [30]:
x=torch.rand(2,3)

In [31]:
x

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [32]:
#addition
x+4

tensor([[4.2239, 4.3023, 4.1784],
        [4.8238, 4.5557, 4.9770]])

In [33]:
#subtraction
x-2

tensor([[-1.7761, -1.6977, -1.8216],
        [-1.1762, -1.4443, -1.0230]])

In [34]:
#multiplication
x*3

tensor([[0.6717, 0.9070, 0.5353],
        [2.4715, 1.6672, 2.9311]])

In [35]:
#divison
x/3

tensor([[0.0746, 0.1008, 0.0595],
        [0.2746, 0.1852, 0.3257]])

In [36]:
(x+4)//3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [37]:
x**2

tensor([[0.0501, 0.0914, 0.0318],
        [0.6787, 0.3089, 0.9546]])

In [38]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [39]:
print(a)
print(b)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])


In [40]:
#addition
a+b

tensor([[0.9717, 1.1950, 1.5354],
        [0.9127, 0.2595, 0.9212]])

In [41]:
#subtraction
a-b

tensor([[-0.0837,  0.7007, -0.0464],
        [ 0.0657,  0.2257,  0.4794]])

In [42]:
#multiplication
a*b

tensor([[0.2343, 0.2343, 0.5888],
        [0.2072, 0.0041, 0.1547]])

In [43]:
a/b

tensor([[ 0.8415,  3.8346,  0.9413],
        [ 1.1552, 14.3533,  3.1705]])

In [44]:
a//b

tensor([[ 0.,  3.,  0.],
        [ 1., 14.,  3.]])

In [45]:
a**b

tensor([[0.6515, 0.9868, 0.7919],
        [0.7388, 0.9763, 0.9243]])

In [46]:
c = torch.tensor([1,-2,3,-4])

In [47]:
torch.abs(c)#it will convert all values into positive value

tensor([1, 2, 3, 4])

In [48]:
torch.neg(c)#it will multiply all values with-1

tensor([-1,  2, -3,  4])

In [49]:
#round
d=torch.tensor([1.9,2.5,3.2,4.8])

In [50]:
torch.round(d)

tensor([2., 2., 3., 5.])

In [51]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [52]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [53]:
#when we want to convert the values into range, like a defined tensor if we want to keep it in a range we can use clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.5000, 3.0000, 3.0000])

# Reduction Operation

In [54]:
#we will only get integers in the range we gave or we defuned
e = torch.randint(size=(2,3),low = 0, high = 10,dtype=torch.float32)

In [55]:
e

tensor([[3., 9., 4.],
        [0., 5., 7.]])

In [56]:
#sum -> will give matrix sum
print(torch.sum(e))
#sum along columns
print(torch.sum(e,dim = 0))
#sum along rows
print(torch.sum(e,dim=1))

tensor(28.)
tensor([ 3., 14., 11.])
tensor([16., 12.])


In [57]:
torch.mean(e)


tensor(4.6667)

In [58]:
torch.mean(e,dim=0)

tensor([1.5000, 7.0000, 5.5000])

In [59]:
#median
torch.median(e)

tensor(4.)

In [60]:
#max and min
torch.max(e)

tensor(9.)

In [61]:
torch.min(e)

tensor(0.)

In [62]:
#product
torch.prod(x)

tensor(0.0054)

In [63]:
#standard deviation
torch.std(x)

tensor(0.3328)

In [64]:
#variance
torch.var(e)

tensor(9.8667)

In [65]:
#will give position of the highest value number in defined tensor
torch.argmax(e)

tensor(1)

In [66]:
#will give position of the least value number in defined tensor
torch.argmin(e)

tensor(3)

# Matrix Operations

In [67]:
f = torch.randint(size=(2,3),low = 0, high = 10)

In [68]:
g = torch.randint(size=(3,2),low=0,high=299)

In [69]:
print(f)
print()
print(g)

tensor([[5, 9, 9],
        [7, 5, 9]])

tensor([[230, 189],
        [ 70,  97],
        [ 64, 148]])


In [70]:
##matrix multiplication
torch.matmul(f,g)

tensor([[2356, 3150],
        [2536, 3140]])

In [71]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [72]:
#transpose
torch.transpose(f,0,1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [73]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [74]:
h

tensor([[7., 7., 8.],
        [3., 6., 1.],
        [5., 5., 0.]])

In [75]:
torch.det(h)

tensor(-120.)

In [76]:
torch.inverse(h)

tensor([[ 4.1667e-02, -3.3333e-01,  3.4167e-01],
        [-4.1667e-02,  3.3333e-01, -1.4167e-01],
        [ 1.2500e-01,  7.4506e-09, -1.7500e-01]])

# Comparison Operations

In [77]:
i = torch.randint(size=(2,3),low = 0,high = 10)
j = torch.randint(size=(2,3),low = 0,high = 10)

print(i)
print()
print(j)

tensor([[4, 3, 8],
        [8, 3, 3]])

tensor([[5, 0, 6],
        [4, 0, 8]])


In [78]:
#greater than
print(i>j)
print()
#less than
print(i<j)
print()
#equal to
print(i==j)
print()
#not equal to
print(i!=j)

#greater than equal to




tensor([[False,  True,  True],
        [ True,  True, False]])

tensor([[ True, False, False],
        [False, False,  True]])

tensor([[False, False, False],
        [False, False, False]])

tensor([[True, True, True],
        [True, True, True]])


# Special Functions

In [79]:
k = torch.randint(size=(2,3),low = 0,high=10,dtype=torch.float32)

In [80]:
k

tensor([[4., 7., 2.],
        [3., 8., 5.]])

In [81]:
#log
torch.log(k)

tensor([[1.3863, 1.9459, 0.6931],
        [1.0986, 2.0794, 1.6094]])

In [82]:
#exp
torch.exp(k)

tensor([[  54.5981, 1096.6332,    7.3891],
        [  20.0855, 2980.9580,  148.4132]])

In [83]:
#sqrt
torch.sqrt(k)

tensor([[2.0000, 2.6458, 1.4142],
        [1.7321, 2.8284, 2.2361]])

In [84]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9991, 0.8808],
        [0.9526, 0.9997, 0.9933]])

In [85]:
torch.softmax(k, dim = 0)#must give dimension and also it only works for float

tensor([[0.7311, 0.2689, 0.0474],
        [0.2689, 0.7311, 0.9526]])

# Inplace Operations

In [86]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print()
print(n)


tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])


In [87]:
m+n # new tensor created in the memory , so if we take a dataset and represent it with tensor and if you do a tensor operation on it , it will create a new tensor it will be problematic so we make the changes in tensor itself

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [88]:
m.add_(n)#inplace operation

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [89]:
print(m)#inplace operation

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])


In [90]:
m.relu_()

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

In [91]:
m

tensor([[1.8746, 1.0939, 0.1762],
        [1.3909, 0.5098, 1.1259]])

# Copying a tensor

In [92]:
a = torch.rand(2,3)

In [93]:
a

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [94]:
b = a

In [95]:
a[0][0]=0

In [96]:
b

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [97]:
a

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [98]:
id(a)

137207349466992

In [99]:
id(b)

137207349466992

In [100]:
b = a.clone()#to copy tensor values above it pointed to same reference point, now it will only copy values


In [101]:
b

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [102]:
a[0][0]=2

In [103]:
a

tensor([[2.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [104]:
b

tensor([[0.0000, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [105]:
id(a)

137207349466992

In [106]:
id(b)

137212417183568

# Tensor Operations on GPU

In [107]:
torch.cuda.is_available()

True

In [108]:
device = torch.device('cuda')

In [109]:
#creating a tensor on gpu
torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [107]:
#moving an existing tensor from cpu to gpu

In [110]:
a = torch.rand(2,3)

In [112]:
a#there is no device in the output we got

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [113]:
b=a.to(device)

In [114]:
b

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]], device='cuda:0')

In [116]:
b + 5

tensor([[5.3957, 5.6017, 5.4234],
        [5.5224, 5.4175, 5.0340]], device='cuda:0')

In [117]:
import time
size = 10000
matrix1 = torch.rand(size,size)
matrix2 = torch.rand(size,size)

start_time = time.time()
result_cpu=torch.matmul(matrix1,matrix2)
cpu_time=time.time()-start_time
print(f"Time on CPU: {cpu_time:.4f} seconds")

matrix1_gpu = matrix1.to('cuda')
matrix2_gpu = matrix2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix1_gpu,matrix2_gpu)
torch.cuda.synchronize()
gpu_time = time.time() - start_time
print(f"time on gpu:{gpu_time:.4f} seconds")

#compare results
print(cpu_time/gpu_time)



Time on CPU: 16.5075 seconds
time on gpu:0.6973 seconds
23.674404315156902


# Reshaping Tensors

In [118]:
a = torch.ones(4,4)

In [119]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [120]:
#a flatten
torch.flatten(a)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [128]:
b = torch.rand(2,3,4)#0,#1,#2

In [129]:
b

tensor([[[0.9893, 0.9873, 0.1471, 0.9790],
         [0.9163, 0.5566, 0.1991, 0.4880],
         [0.2634, 0.4260, 0.2144, 0.8844]],

        [[0.3690, 0.2746, 0.4782, 0.8778],
         [0.4314, 0.1135, 0.7670, 0.5416],
         [0.4059, 0.3982, 0.4293, 0.7526]]])

In [131]:
b.shape

torch.Size([2, 3, 4])

In [130]:
#permute
b.permute(2,0,1).shape#above when we created value those dimension will have indices,with those indices here we define new dimension , so whatever dimension value is there in the instialized tensor will replace the indices value in this function

torch.Size([4, 2, 3])

In [134]:
#unsqueeze
#image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape#when you want to add a dimension

torch.Size([1, 226, 226, 3])

In [135]:
s=torch.rand(3,3,3)

In [136]:
s

tensor([[[0.4961, 0.5405, 0.5098],
         [0.5352, 0.6615, 0.2910],
         [0.9676, 0.7878, 0.4111]],

        [[0.9265, 0.8062, 0.1623],
         [0.3418, 0.8456, 0.7560],
         [0.6895, 0.9839, 0.2529]],

        [[0.6561, 0.6114, 0.3198],
         [0.9397, 0.3207, 0.4245],
         [0.9732, 0.0611, 0.7100]]])

In [137]:
print(c)

tensor([[[2.8028e-01, 4.8327e-01, 5.1544e-01],
         [9.2848e-01, 5.5392e-01, 3.4829e-01],
         [8.1033e-01, 9.4569e-01, 1.2517e-06],
         ...,
         [9.0045e-01, 8.4221e-05, 8.7528e-02],
         [4.5739e-01, 3.5261e-01, 3.3707e-01],
         [6.5877e-01, 3.4774e-01, 8.6727e-02]],

        [[7.2294e-01, 8.9324e-01, 4.1058e-01],
         [2.2226e-01, 8.4423e-01, 3.6375e-01],
         [3.6770e-01, 4.0387e-01, 2.6932e-01],
         ...,
         [7.0231e-01, 5.3409e-01, 3.5369e-01],
         [3.1525e-01, 1.5396e-01, 7.0509e-01],
         [3.0755e-02, 2.5839e-01, 1.0593e-02]],

        [[6.0133e-01, 8.2577e-01, 8.5904e-02],
         [2.4048e-01, 4.4634e-01, 3.6338e-01],
         [8.2614e-01, 6.0323e-01, 1.5917e-01],
         ...,
         [1.7071e-01, 9.1195e-01, 2.5689e-01],
         [6.8908e-01, 1.7831e-01, 4.9222e-01],
         [4.7476e-01, 1.8750e-01, 3.3622e-01]],

        ...,

        [[4.6439e-01, 2.9639e-01, 9.2982e-01],
         [2.8926e-01, 4.0323e-01, 3.7675e-01]

In [138]:
s=(2,3,4)#2 means depth ,3means rows,4 means columns

In [139]:
d = torch.rand(1,20)#removes dimension

In [140]:
d.squeeze(0).shape

torch.Size([20])

# Numpy and pytorch

In [141]:
import numpy as np

In [143]:
a = torch.tensor([1,2,3])

In [144]:
b=a.numpy()

In [145]:
type(b)

numpy.ndarray

In [146]:
c = np.array([1,2,4])

In [147]:
torch.from_numpy(c)

tensor([1, 2, 4])